### ISSUE TITLE
Discord RPC Bug.

### ISSUE THREAD

**Issue by Gaeta** [cryptofyre/Apple-Music-Electron#26]
When the user minimize/close the window or focus on something else the Discord RPC will start bugging saying its paused and then goes back to saying the song then back to pause. This repeats infinity.

It only stops if your focused on the application.

**Comment by devilAPI** [comment]
It's not showing at all, for me

**Comment by iiFir3z** [comment]
Ill check it out.

**Comment by Dream-cake** [comment]
I can send a video if you wish

**Comment by devilAPI** [comment]
rpc works, but same issue, sometimes the time goes back, sometimes it goes forward. weird.

**Comment by Dream-cake** [comment]
Any update on this?

**Comment by cryptofyre** [comment]
I have figured out a solution and it should be out at some point this week alongside some other fixes and improvements.

**Comment by Dream-cake** [comment]
Can I see the code?

> I have figured out a solution and it should be out at some point this week alongside some other fixes and improvements.

**Comment by Choccreamyum12** [comment]
My discord isn't detecting it at all

**Comment by cryptofyre** [comment]
This should now work as of the [v1.5.6 release](https://github.com/cryptofyre/Apple-Music-Electron/releases/tag/1.5.7)! If someone could test this and notify me that would be greatly appreciated!

**Comment by Shriukan** [comment]
Discord is detecting AM here, but still shows paused when not focusing.
![image](https://user-images.githubusercontent.com/6706006/116444337-e9e8cf00-a854-11eb-9bc4-df6c398dc596.png)

**Comment by cryptofyre** [comment]
Thanks! I'm glad it ended up working out for you!
