### ISSUE TITLE
Login failed with "not available in your region", although Apple Music is available on my country.

### ISSUE THREAD

**Issue by LaruYan** [cryptofyre/Apple-Music-Electron#82]
## Symptoms
A message appears and fails to log in, after Apple ID credentials were input.
```
Apple Music is not available in your country or region.
```
![login fails with region lock](https://user-images.githubusercontent.com/13941966/120419095-b857ac00-c39c-11eb-8169-5cb3088ba7d2.png)

## Expected
Apple Music on electron logs in and able to play musics.

## Environment
Version: [2.1.0](https://github.com/cryptofyre/Apple-Music-Electron/releases/tag/v2.1.0)
OS: Windows 10 20H1 x86-64 (19043.1023)
CPU: Intel Core i7-8650U
RAM: 16GB
Locale of Windows & Store: English (United States) `en_US`
Locale of Apple ID: South Korea `ko` ([where Apple Music is available and Apple TV is partially available(synced videos only)](https://support.apple.com/HT204411#apac))
Does works on [browser](https://music.apple.com/): yes
Have iTunes installed: yes, via Microsoft Store
Can play music on official Apple apps: yes.
Have Apple Music subscriptions: active, paid monthly.
Have an antivirus: yes. Kaspersky 2021 (patch b applied)

## Console logs
```
PS > & '.\Apple Music.lnk'
[DiscordRPC] Initializing Client.
---------------------------------------------------------------------
Apple-Music-Electron application has started.
---------------------------------------------------------------------
12:32:46.158 > [Apple-Music-Electron] Application is Ready.
12:32:46.165 > [Apple-Music-Electron] Configuration File:
12:32:46.166 > {
  css: {
    _notice_: 'This section is for manually disabling/enabling features.',
    _removeAppleLogo_comment: 'Removes Apple Logo when enabled. (true by default)',
    removeAppleLogo: true,
    _removeUpsell_comment: 'Removes the open iTunes button if enabled (true by default)',
    removeUpsell: true,
    _macosWindow_comment: 'This enables the MacOS window frame. (false by default)',
    macosWindow: true
  },
  preferences: {
    _notice_: 'This is the basic user preferences. Modify to your liking below.',
    _defaultTheme_comment: 'Default UI theme (Light/Dark) or leave empty to detect from system.',
    defaultTheme: '',
    _cssTheme_comment: 'If you are using a custom CSS theme, set it below, otherwise leave empty.',
    cssTheme: '',
    _closeButtonMinimize_comment: 'Should the close button minimize your apple music (true) or should it quit the app (false). (true by default)',
    closeButtonMinimize: true,
    _discordRPC_comment: 'Enable/Disable Discord Rich Presence. (true by default)',
    discordRPC: true,
    _playbackNotifications_comment: 'Enabling this means you will get notifications when you change song. The notificationsMinimized option force notifications to only appear if the app is hidden / minimized.',
    playbackNotifications: true,
    notificationsMinimized: true,
    _trayTooltipSongName_comment: 'Enabling this option allows you to see the song name in the tooltip on the taskbar when the application is minimized to the tray.',
    trayTooltipSongName: true
  },
  advanced: {
    allowMultipleInstances: false,
    allowRunningInsecureContent: true,
    allowSetMenu: false,
    autoUpdaterBetaBuilds: false,
    enableLogging: true,
    forceApplicationLanguage: '',
    menuBarVisible: false,
    removeScrollbars: true,
    siteDetection: false,
    useBeta: true
  }
}
12:32:46.289 > [AutoUpdater] Checking for updates...
12:32:46.291 > Checking for update
12:32:46.293 > [Language] Found: us | System Language: us
12:32:46.295 > [Apple-Music-Electron] The chosen website is https://beta.music.apple.com/us?l=us
12:32:47.281 > [DiscordRPC] Error: Error: Could not connect
12:32:47.283 > [DiscordRPC] Disconnecting from Discord.
12:32:48.842 > Update for version 2.1.0 is not available (latest version: 2.1.0, downgrade is disallowed).
12:32:48.844 > checkForUpdatesAndNotify called, downloadPromise is null
12:32:48.845 > [AutoUpdater] Finished checking for updates.
12:32:49.725 > [Apple-Music-Electron] Website has been loaded!
12:32:49.781 > [CSS] Apple Logo Removed.
(node:23096) UnhandledPromiseRejectionWarning: Error: Script failed to execute, this normally means an error was thrown. Check the renderer console for the error.
    at WebFrame.e.startsWith.e.startsWith.WebFrame.<computed> [as _executeJavaScript] (electron/js2c/sandbox_bundle.js:69:1645)
    at electron/js2c/sandbox_bundle.js:93:471
    at EventEmitter.<anonymous> (electron/js2c/sandbox_bundle.js:77:388)
    at EventEmitter.emit (electron/js2c/sandbox_bundle.js:156:3752)
    at Object.onMessage (electron/js2c/sandbox_bundle.js:129:1369)
(Use `Apple Music --trace-warnings ...` to show where the warning was created)
(node:23096) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:23096) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
12:32:49.811 > [CSS] Removed upsell.
12:32:49.814 > [CSS] Enabled custom MacOS Window Frame
12:32:50.807 > [CSS] Apple Logo Removed.
12:32:50.809 > [CSS] Apple Logo Space Displaced.
12:32:50.810 > [CSS] Removed upsell.
(node:23096) UnhandledPromiseRejectionWarning: Error: An object could not be cloned.
    at EventEmitter.i.send (electron/js2c/sandbox_bundle.js:81:381)
    at EventEmitter.<anonymous> (electron/js2c/sandbox_bundle.js:77:370)
(node:23096) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
12:33:05.255 > [CSS] Apple Logo Removed.
12:33:05.256 > [CSS] Apple Logo Space Displaced.
12:33:05.257 > [CSS] Removed upsell.
12:33:05.258 > [CSS] Enabled custom MacOS Window Frame
12:33:07.004 > [CSS] Apple Logo Removed.
12:33:07.005 > [CSS] Apple Logo Space Displaced.
12:33:07.007 > [CSS] Removed upsell.
12:33:07.008 > [CSS] Enabled custom MacOS Window Frame
12:33:43.845 > [CSS] Apple Logo Removed.
12:33:43.848 > [CSS] Apple Logo Space Displaced.
12:33:43.851 > [CSS] Removed upsell.
12:33:43.858 > [CSS] Enabled custom MacOS Window Frame
12:33:55.810 > ---------------------------------------------------------------------
12:33:55.811 > Application Closing...
12:33:55.813 > ---------------------------------------------------------------------
```

**Comment by cryptofyre** [comment]
Its not actually region locked. Apple fucked up authentication on their servers at the moment. Should be back to normal soon.

**Comment by LaruYan** [comment]
I have cloned source code, then did open devTools and watched Networks pane.

I've got HTTP 403 Forbidden after successful log in to Apple ID, then kicked out back to log in window, saying region lock.

![forbidden for region lock](https://user-images.githubusercontent.com/13941966/120486346-eb775b00-c3ef-11eb-9584-33c1f907040b.png)

`https://buy.music.apple.com/account/web/auth` 403 Forbidden;
```
{
    "ineligibilityReason": "IneligibleStoreFront"
}
```

**Comment by cryptofyre** [comment]
Sometimes I hate this company, I'm bringing up an email to them.

**Comment by LaruYan** [comment]
Thank you. Hope region lock goes away.

**Comment by cryptofyre** [comment]
Issue has been fixed should be able to login like normal again.

**Comment by vxsl** [comment]
@cryptofyre same issue persists in Canada with the latest master.

## Environment
Version: 2.1.0 (9f5c07e87fa97947ce7a2b7784f78a09dbb11122)
OS: Arch Linux 5.12.1-arch1-1
CPU: Ryzen 3800x
RAM: 32GB
Locale of Linux: English (United States) en_US
Locale of Apple ID: Canada
Does works on browser: yes
Have iTunes installed: yes, via Wine
Can play music on official Apple apps: yes.
Have Apple Music subscriptions: active, paid monthly.
Have an antivirus: no

## Console logs
```
$ electron --enable-accelerated-mjpeg-decode --enable-accelerated-video --ignore-gpu-blacklist --enable-native-gpu-memory-buffers --enable-gpu-rasterization .
[DiscordRPC] Initializing Client.
[Apple-Music-Electron] Application is Ready.
[Apple-Music-Electron] Configuration File:
{
css: {
_notice_: 'This section is for manually disabling/enabling features.',
_removeAppleLogo_comment: 'Removes Apple Logo when enabled. (true by default)',
removeAppleLogo: true,
_removeUpsell_comment: 'Removes the open iTunes button if enabled (true by default)',
removeUpsell: true,
_macosWindow_comment: 'This enables the MacOS window frame. (false by default)',
macosWindow: true
},
preferences: {
_notice_: 'This is the basic user preferences. Modify to your liking below.',
_defaultTheme_comment: 'Default UI theme (Light/Dark) or leave empty to detect from system.',
defaultTheme: '',
_cssTheme_comment: 'If you are using a custom CSS theme, set it below, otherwise leave empty.',
cssTheme: '',
_closeButtonMinimize_comment: 'Should the close button minimize your apple music (true) or should it quit the app (false). (true by default)',
closeButtonMinimize: true,
_discordRPC_comment: 'Enable/Disable Discord Rich Presence. (true by default)',
discordRPC: true,
_playbackNotifications_comment: 'Enabling this means you will get notifications when you change song. The notificationsMinimized option force notifications to only appear if the app is hidden / minimized.',
playbackNotifications: true,
notificationsMinimized: true,
_trayTooltipSongName_comment: 'Enabling this option allows you to see the song name in the tooltip on the taskbar when the application is minimizedto the tray.',
trayTooltipSongName: true
},
advanced: {
allowMultipleInstances: false,
allowRunningInsecureContent: true,
allowSetMenu: false,
autoUpdaterBetaBuilds: false,
enableLogging: true,
forceApplicationLanguage: '',
menuBarVisible: false,
removeScrollbars: true,
siteDetection: false,
useBeta: true
}
}
---------------------------------------------------------------------
Apple-Music-Electron application has started.
---------------------------------------------------------------------
10:52:06.163 › [AutoUpdater] Checking for updates...
10:52:06.166 › APPIMAGE env is not defined, current application is not an AppImage
10:52:06.166 › [Apple-Music-Electron] The chosen website is https://beta.music.apple.com/us?l=us
10:52:06.173 › [AutoUpdater] Finished checking for updates.
10:52:06.190 › [DiscordRPC] Error: Error: Could not connect
10:52:06.191 › [DiscordRPC] Disconnecting from Discord.
10:52:06.978 › [Apple-Music-Electron] Website has been loaded!
10:52:06.997 › [JS] './assets/js/removeAppleLogo.js' successfully injected.
10:52:06.998 › [JS] './assets/js/removeUpsell.js' successfully injected.
10:52:06.998 › [JS] './assets/js/macosWindowFrame.js' successfully injected.
10:52:07.571 › [JS] './assets/js/removeAppleLogo.js' successfully injected.
10:52:07.571 › [JS] './assets/js/removeUpsell.js' successfully injected.
(node:1705) UnhandledPromiseRejectionWarning: Error: An object could not be cloned.
at EventEmitter.i.send (electron/js2c/sandbox_bundle.js:57:368)
at EventEmitter.<anonymous> (electron/js2c/sandbox_bundle.js:53:357)
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:1705) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function withouta catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1705) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
10:52:10.881 › [JS] './assets/js/removeAppleLogo.js' successfully injected.
10:52:10.882 › [JS] './assets/js/removeUpsell.js' successfully injected.
10:52:10.882 › [JS] './assets/js/macosWindowFrame.js' successfully injected.
10:52:11.593 › [JS] './assets/js/removeAppleLogo.js' successfully injected.
10:52:11.594 › [JS] './assets/js/removeUpsell.js' successfully injected.
10:52:11.594 › [JS] './assets/js/macosWindowFrame.js' successfully injected.
10:52:29.507 › [JS] './assets/js/removeAppleLogo.js' successfully injected.
10:52:29.508 › [JS] './assets/js/removeUpsell.js' successfully injected.
10:52:29.508 › [JS] './assets/js/macosWindowFrame.js' successfully injected.
```

**Comment by cryptofyre** [comment]
Seem's Apple didn't change back CORS on the Canadian storefront. I'll send them an email to get it fixed.

**Comment by vxsl** [comment]
Sounds good. Thanks for all your hard work on this.
